server:
  port: 8888

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/longzhou3/spring-boot-cloud
          search-paths: config-repo
          username: longzhou3                                             # git仓库的账号
          password: lz198764                                            # git仓库的密码
  rabbitmq:
    host: 47.106.89.28
    port: 5672
    virtualHost: /
    username: root
    password: 123456

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
