server:
  port: 8888

management:
  security:
    enabled: false
  context-path: /mgmt

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    health-check-url-path: /health
    status-page-url-path: /info
    metadata-map:
      management.context-path: ${management.context-path}
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@127.0.0.1:8761/eureka/


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/longzhou3/spring-boot-cloud
          search-paths: config-repo
          username: longzhou3                                             # git仓库的账号
          password: lz198764                                            # git仓库的密码
  rabbitmq:
    host: 47.106.89.28
    port: 5672
    virtualHost: /
    username: root
    password: 123456

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
